version: '3'
services:
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: nextcloud_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextcloud_network
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      MYSQL_PASSWORD: nextcloud_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_HOST: db
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    networks:
      - nextcloud_network
    restart: always

networks:
  nextcloud_network:
    driver: bridge

volumes:
  db_data:
  nextcloud_data:
